# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BYl9us1afRVRtx9guYhjidmoTBa8XSk
"""

import matplotlib.pyplot as plt
import numpy as np

x= np.array([0,6])
y= np.array([0,250])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([0,10,20,30,40,50,60,70,80,90,100])
y= np.array([30,55,25,70,40,50,30,60,30,70,60])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([0,10,20,30,40,50,60,70,80,90,100])
y= np.array([30,55,25,70,40,50,30,60,30,70,60])

plt.plot(y, marker = "o", ms=20)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([0,10,20,30,40,50,60,70,80,90,100])
y= np.array([30,55,25,70,40,50,30,60,30,70,60])

plt.plot(y, marker = "o", ms=20, mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1= np.array([0,10,20,30,40,50,60,70,80,90,100])
y1= np.array([30,55,25,70,40,50,30,60,30,70,60])
x2= np.array([30,55,25,70,40,50,30,60,30,70,60])
y2= np.array([0,10,20,30,40,50,60,70,80,90,100])

plt.plot(x1,x2,y1,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([0,10,20,30,40,50,60,70,80,90,100])
y= np.array([30,55,25,70,40,50,30,60,30,70,60])


plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([0,10,20,30,40,50,60,70,80,90,100])
y= np.array([30,55,25,70,40,50,30,60,30,70,60])
plt.scatter(x,y,color='red')

x= np.array([30,55,25,70,40,50,30,60,30,70,60])
y= np.array([0,10,20,30,40,50,60,70,80,90,100])
plt.scatter(x,y,color='green')


plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([0,10,20,30,40,50])
y= np.array([30,55,25,70,40,50])
mycolor=['red','green','purple','lime','aqua','yellow']


plt.scatter(x,y,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([0,10,20,30,40,50])
y= np.array([30,55,25,70,40,50])
mycolor=['red','green','purple','lime','aqua','yellow']
size=[12,34,12,34,45,22]

plt.scatter(x,y,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array(['A','B','C','D'])
y= np.array([30,55,25,70])



plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array(['A','B','C','D'])
y= np.array([30,55,25,70])



plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array(['A','B','C','D'])
y= np.array([30,55,25,70])


plt.bar(y,y,width=0.1)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x= np.array([30,55,25,70])



plt.pie(x)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x= np.array([30,55,25,70])
mylabels=["Apple","Banana","Cherry","Dates"]

plt.pie(x,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x= np.array([30,55,25,70])
mylabels=["Apple","Banana","Cherry","Dates"]

plt.pie(x,labels=mylabels,startangle=90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x= np.array([30,55,25,70])
mylabels=["Apple","Banana","Cherry","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x= np.array([30,55,25,70])
mylabels=["Apple","Banana","Cherry","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode,shadow=True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x= np.array([30,55,25,70])
mylabels=["apples","bananas","Cherries","Dates"]
mycolors=["black","hotpink","b","#4CAF50"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode,colors=mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x= np.array([30,55,25,70])
mylabels=["apples","bananas","Cherries","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels)
plt.legend()
plt.show()